[book]
title = "Par Documentation"
authors = ["s15n"]
description = "Documentation for the Par programming language"
src = "src"
language = "en"
multilingual = false

[output.html]
theme = "par-theme"
git-repository-url = "https://github.com/faiface/par-lang/tree/main/docs"
mathjax-support = true

[output.html.code.hidelines]
par = "?"